"""
Assessment 2: Translation with LLM
------------------------------------
This script consumes Hindi translations generated by an LLM (Claude, by
Anthropic) for 200 English sentences sampled from the Assessment 1 cleaned
dataset, then computes BLEU / CHRF / TER scores against the reference Hindi
sentences from the original parallel corpus, and produces the required
Excel and .txt deliverables.

LLM used: Claude (Anthropic) -- NOT Google Translate, NOT Helsinki-NLP.
Translations were generated by directly prompting the LLM with each English
sentence and recording its Hindi output (see claude_translations.json).

Usage:
    python translate_with_llm.py
"""

import json
import pandas as pd
import sacrebleu

SAMPLE_FILE = "sampled_200.xlsx"
TRANSLATIONS_FILE = "claude_translations.json"
OUTPUT_EXCEL = "translation_output.xlsx"
OUTPUT_SCORES = "translation_scores.txt"

MODEL_NAME = "Claude (Anthropic LLM)"


def main():
    df = pd.read_excel(SAMPLE_FILE)
    english_sentences = df["English Sentence"].tolist()
    reference_hindi = df["Hindi Sentence"].tolist()

    with open(TRANSLATIONS_FILE, "r", encoding="utf-8") as f:
        translations_map = json.load(f)

    translations = [translations_map[str(i)] for i in range(len(english_sentences))]

    # Submission format: Column A = Original English sentence, Column B = Model-generated Hindi translation
    out_df = pd.DataFrame({
        "Original English sentence": english_sentences,
        "Model-generated Hindi translation": translations,
    })
    out_df.to_excel(OUTPUT_EXCEL, index=False, engine="openpyxl")
    print(f"Saved translation output to {OUTPUT_EXCEL} ({len(out_df)} rows)")

    # Score against reference Hindi sentences using sacrebleu
    hyps = translations
    refs = reference_hindi

    bleu = sacrebleu.corpus_bleu(hyps, [refs])
    chrf = sacrebleu.corpus_chrf(hyps, [refs])
    ter = sacrebleu.corpus_ter(hyps, [refs])

    score_text = (
        "Assessment 2: Translation with LLM - Evaluation Scores\n"
        "=========================================================\n"
        f"LLM used for translation: {MODEL_NAME}\n"
        f"Number of sentences evaluated: {len(hyps)}\n\n"
        f"BLEU score : {bleu.score:.4f}\n"
        f"CHRF score : {chrf.score:.4f}\n"
        f"TER score  : {ter.score:.4f}\n"
    )
    with open(OUTPUT_SCORES, "w", encoding="utf-8") as f:
        f.write(score_text)

    print("\n" + score_text)
    print(f"Saved scores to {OUTPUT_SCORES}")


if __name__ == "__main__":
    main()
